"""initial schema

Revision ID: d29733786f05
Revises: 
Create Date: 2026-03-01 14:47:23.492537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd29733786f05'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('user_points', sa.Integer(), nullable=False),
    sa.Column('user_rank', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('user_points >= 0', name='check_username_more_than_zero'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('goals',
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('goal_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('start_day', sa.Date(), nullable=False),
    sa.Column('target_day', sa.Date(), nullable=False),
    sa.Column('status_against_goal', sa.String(length=200), nullable=False),
    sa.Column('weekday_available_time', sa.Integer(), nullable=False),
    sa.Column('weekends_available_time', sa.Integer(), nullable=False),
    sa.Column('total_estimated_time', sa.Integer(), nullable=False),
    sa.Column('task_creation_rule', sa.String(length=800), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('length(goal_name) > 0', name='check_goal_name_greater_than_zero'),
    sa.CheckConstraint('length(status_against_goal) > 0', name='check_status_against_goal_greater_than_zero'),
    sa.CheckConstraint('start_day <= target_day', name='check_start_before_target'),
    sa.CheckConstraint('start_day > CURRENT_DATE', name='check_start_before_now'),
    sa.CheckConstraint('target_day > CURRENT_DATE', name='check_target_before_now'),
    sa.CheckConstraint('total_estimated_time > 0', name='check_total_estimated_time_greater_than_zero'),
    sa.CheckConstraint('weekday_available_time <= 720', name='check_weekday_available_time_greater_than_720'),
    sa.CheckConstraint('weekday_available_time > 0', name='check_weekday_available_time_greater_than_zero'),
    sa.CheckConstraint('weekends_available_time <= 720', name='check_weekends_available_time_greater_than_720'),
    sa.CheckConstraint('weekends_available_time > 0', name='check_weekends_available_time_greater_than_zero'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('goal_id')
    )
    op.create_table('password_reset_tokens',
    sa.Column('password_reset_token_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_prefix', sa.String(length=6), nullable=False),
    sa.Column('hashed_token', sa.String(length=72), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('password_reset_token_id'),
    sa.UniqueConstraint('hashed_token')
    )
    op.create_table('refresh_tokens',
    sa.Column('refresh_token_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_prefix', sa.String(length=6), nullable=False),
    sa.Column('hashed_token', sa.String(length=72), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('refresh_token_id'),
    sa.UniqueConstraint('hashed_token')
    )
    op.create_table('goals_tasks',
    sa.Column('goal_task_id', sa.Integer(), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('goal_task_name', sa.String(length=100), nullable=False),
    sa.Column('goal_task_status', sa.String(), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=False),
    sa.Column('estimated_time', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('"order" > 0', name='check_order_greater_than_zero'),
    sa.CheckConstraint('deadline > CURRENT_DATE', name='check_deadline_before_now'),
    sa.CheckConstraint('estimated_time <= 720', name='check_estimated_time_greater_than_1440'),
    sa.CheckConstraint('estimated_time > 0', name='check_estimated_time_greater_than_zero'),
    sa.CheckConstraint('length(goal_task_name) > 0', name='check_goal_task_name_greater_than_zero'),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.goal_id'], ),
    sa.PrimaryKeyConstraint('goal_task_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('goals_tasks')
    op.drop_table('refresh_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_table('goals')
    op.drop_table('users')
    # ### end Alembic commands ###
